version: "3.8"

services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: back-container
    command: uvicorn main:app --host 0.0.0.0 --port 8000 
    ports:
      - 8000:8000
    depends_on:
      - db
