"""add alias

Revision ID: 54c77c91f11d
Revises: b2faa254495a
Create Date: 2024-04-13 19:32:38.732392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c77c91f11d'
down_revision: Union[str, None] = 'b2faa254495a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('alias', sa.Text(), nullable=True))
    op.add_column('jokes', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_constraint('jokes_alias_id_fkey', 'jokes', type_='foreignkey')
    op.create_foreign_key(None, 'jokes', 'jokes_category', ['category_id'], ['category_id'])
    op.drop_column('jokes', 'alias_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jokes', sa.Column('alias_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jokes', type_='foreignkey')
    op.create_foreign_key('jokes_alias_id_fkey', 'jokes', 'jokes_category', ['alias_id'], ['category_id'])
    op.drop_column('jokes', 'category_id')
    op.drop_column('jokes', 'alias')
    # ### end Alembic commands ###
