"""init

Revision ID: 6155cb87f312
Revises: 
Create Date: 2024-04-13 19:03:56.227595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6155cb87f312'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jokes_alias',
    sa.Column('alias_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('alias_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jokes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('alias_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alias_id'], ['jokes_alias.alias_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favourites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joke_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['joke_id'], ['jokes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'joke_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourites')
    op.drop_table('jokes')
    op.drop_table('users')
    op.drop_table('jokes_alias')
    # ### end Alembic commands ###
