"""name change

Revision ID: b2faa254495a
Revises: 6155cb87f312
Create Date: 2024-04-13 19:15:26.439808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2faa254495a'
down_revision: Union[str, None] = '6155cb87f312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jokes_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.execute("DROP TABLE jokes_alias CASCADE;")
    op.create_foreign_key(None, 'jokes', 'jokes_category', ['alias_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jokes', type_='foreignkey')
    op.create_foreign_key('jokes_alias_id_fkey', 'jokes', 'jokes_alias', ['alias_id'], ['alias_id'])
    op.create_table('jokes_alias',
    sa.Column('alias_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('alias_id', name='jokes_alias_pkey')
    )
    op.drop_table('jokes_category')
    # ### end Alembic commands ###
